/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router; progression entry is kept in sync until the next generator run.
import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CrewRouteImport } from './routes/crew'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as JoinRouteImport } from './routes/join'
import { Route as MeetRouteImport } from './routes/meet'
import { Route as MusicRouteImport } from './routes/music'
import { Route as OniAiRouteImport } from './routes/oni-ai'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressionRouteImport } from './routes/progression'

const IndexRoute=IndexRouteImport.update({id:'/',path:'/',getParentRoute:()=>rootRouteImport} as any)
const AdminRoute=AdminRouteImport.update({id:'/admin',path:'/admin',getParentRoute:()=>rootRouteImport} as any)
const CrewRoute=CrewRouteImport.update({id:'/crew',path:'/crew',getParentRoute:()=>rootRouteImport} as any)
const GalleryRoute=GalleryRouteImport.update({id:'/gallery',path:'/gallery',getParentRoute:()=>rootRouteImport} as any)
const GarageRoute=GarageRouteImport.update({id:'/garage',path:'/garage',getParentRoute:()=>rootRouteImport} as any)
const JoinRoute=JoinRouteImport.update({id:'/join',path:'/join',getParentRoute:()=>rootRouteImport} as any)
const MeetRoute=MeetRouteImport.update({id:'/meet',path:'/meet',getParentRoute:()=>rootRouteImport} as any)
const MusicRoute=MusicRouteImport.update({id:'/music',path:'/music',getParentRoute:()=>rootRouteImport} as any)
const OniAiRoute=OniAiRouteImport.update({id:'/oni-ai',path:'/oni-ai',getParentRoute:()=>rootRouteImport} as any)
const ProfileRoute=ProfileRouteImport.update({id:'/profile',path:'/profile',getParentRoute:()=>rootRouteImport} as any)
const ProgressionRoute=ProgressionRouteImport.update({id:'/progression',path:'/progression',getParentRoute:()=>rootRouteImport} as any)

export interface FileRoutesByFullPath {'/':typeof IndexRoute;'/admin':typeof AdminRoute;'/crew':typeof CrewRoute;'/gallery':typeof GalleryRoute;'/garage':typeof GarageRoute;'/join':typeof JoinRoute;'/meet':typeof MeetRoute;'/music':typeof MusicRoute;'/oni-ai':typeof OniAiRoute;'/profile':typeof ProfileRoute;'/progression':typeof ProgressionRoute}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {__root__:typeof rootRouteImport;'/':typeof IndexRoute;'/admin':typeof AdminRoute;'/crew':typeof CrewRoute;'/gallery':typeof GalleryRoute;'/garage':typeof GarageRoute;'/join':typeof JoinRoute;'/meet':typeof MeetRoute;'/music':typeof MusicRoute;'/oni-ai':typeof OniAiRoute;'/profile':typeof ProfileRoute;'/progression':typeof ProgressionRoute}
export interface FileRouteTypes {fileRoutesByFullPath:FileRoutesByFullPath;fullPaths:keyof FileRoutesByFullPath;fileRoutesByTo:FileRoutesByTo;to:keyof FileRoutesByTo;id:keyof FileRoutesById;fileRoutesById:FileRoutesById}
export interface RootRouteChildren {IndexRoute:typeof IndexRoute;AdminRoute:typeof AdminRoute;CrewRoute:typeof CrewRoute;GalleryRoute:typeof GalleryRoute;GarageRoute:typeof GarageRoute;JoinRoute:typeof JoinRoute;MeetRoute:typeof MeetRoute;MusicRoute:typeof MusicRoute;OniAiRoute:typeof OniAiRoute;ProfileRoute:typeof ProfileRoute;ProgressionRoute:typeof ProgressionRoute}

declare module '@tanstack/react-router' { interface FileRoutesByPath {
'/':{id:'/';path:'/';fullPath:'/';preLoaderRoute:typeof IndexRouteImport;parentRoute:typeof rootRouteImport}
'/admin':{id:'/admin';path:'/admin';fullPath:'/admin';preLoaderRoute:typeof AdminRouteImport;parentRoute:typeof rootRouteImport}
'/crew':{id:'/crew';path:'/crew';fullPath:'/crew';preLoaderRoute:typeof CrewRouteImport;parentRoute:typeof rootRouteImport}
'/gallery':{id:'/gallery';path:'/gallery';fullPath:'/gallery';preLoaderRoute:typeof GalleryRouteImport;parentRoute:typeof rootRouteImport}
'/garage':{id:'/garage';path:'/garage';fullPath:'/garage';preLoaderRoute:typeof GarageRouteImport;parentRoute:typeof rootRouteImport}
'/join':{id:'/join';path:'/join';fullPath:'/join';preLoaderRoute:typeof JoinRouteImport;parentRoute:typeof rootRouteImport}
'/meet':{id:'/meet';path:'/meet';fullPath:'/meet';preLoaderRoute:typeof MeetRouteImport;parentRoute:typeof rootRouteImport}
'/music':{id:'/music';path:'/music';fullPath:'/music';preLoaderRoute:typeof MusicRouteImport;parentRoute:typeof rootRouteImport}
'/oni-ai':{id:'/oni-ai';path:'/oni-ai';fullPath:'/oni-ai';preLoaderRoute:typeof OniAiRouteImport;parentRoute:typeof rootRouteImport}
'/profile':{id:'/profile';path:'/profile';fullPath:'/profile';preLoaderRoute:typeof ProfileRouteImport;parentRoute:typeof rootRouteImport}
'/progression':{id:'/progression';path:'/progression';fullPath:'/progression';preLoaderRoute:typeof ProgressionRouteImport;parentRoute:typeof rootRouteImport}
}}
const rootRouteChildren:RootRouteChildren={IndexRoute,AdminRoute,CrewRoute,GalleryRoute,GarageRoute,JoinRoute,MeetRoute,MusicRoute,OniAiRoute,ProfileRoute,ProgressionRoute}
export const routeTree=rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {interface Register {ssr:true;router:Awaited<ReturnType<typeof getRouter>>;config:Awaited<ReturnType<typeof startInstance.getOptions>>}}
