import { useEffect, useMemo, useRef, type CSSProperties } from "react";
import oniCharacter from "@/assets/oni-character.webp";
import type { OniState } from "@/lib/oni-emotion";
import { getOniRigAsset, getOniRigAssetCoverage } from "./oni-rig-assets";
import { ONI_RIG_EXPRESSIONS } from "./oni-rig-expression";
import { ONI_RIG_LAYERS, ONI_RIG_STATE_INTENSITY } from "./oni-rig-manifest";
import { ONI_WEB_LIVE2D_MOTIONS } from "./oni-web-live2d";
import "./OniWebRig.css";
type Props={state:OniState;glow:number;speaking?:boolean}; type RigStyle=CSSProperties&Record<`--oni-${string}`,string>; type Look={x:number;y:number};
const clamp=(v:number)=>Math.max(-1,Math.min(1,v));
export function OniWebRig({state,glow,speaking=false}:Props){
 const rootRef=useRef<HTMLDivElement|null>(null),frameRef=useRef<number|null>(null),targetRef=useRef<Look>({x:0,y:0}),currentRef=useRef<Look>({x:0,y:0});
 useEffect(()=>{const root=rootRef.current;if(!root||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;let running=true,resetTimer=0;const setTarget=(cx:number,cy:number)=>{const r=root.getBoundingClientRect();if(!r.width||!r.height)return;targetRef.current={x:clamp((cx-r.left-r.width/2)/(r.width/2)),y:clamp((cy-r.top-r.height*.35)/(r.height*.55))};clearTimeout(resetTimer);resetTimer=window.setTimeout(()=>targetRef.current={x:0,y:0},1800)};const pointer=(e:PointerEvent)=>setTarget(e.clientX,e.clientY);const touch=(e:TouchEvent)=>{const t=e.touches[0];if(t)setTarget(t.clientX,t.clientY)};const visibility=()=>{running=!document.hidden;targetRef.current={x:0,y:0};if(running&&frameRef.current===null)frameRef.current=requestAnimationFrame(tick)};const tick=()=>{if(!running){frameRef.current=null;return}const c=currentRef.current,t=targetRef.current,x=c.x+(t.x-c.x)*.14,y=c.y+(t.y-c.y)*.14;currentRef.current={x,y};root.style.setProperty("--oni-look-x",x.toFixed(3));root.style.setProperty("--oni-look-y",y.toFixed(3));frameRef.current=requestAnimationFrame(tick)};window.addEventListener("pointermove",pointer,{passive:true});window.addEventListener("pointerdown",pointer,{passive:true});window.addEventListener("touchstart",touch,{passive:true});window.addEventListener("touchmove",touch,{passive:true});document.addEventListener("visibilitychange",visibility);frameRef.current=requestAnimationFrame(tick);return()=>{running=false;clearTimeout(resetTimer);window.removeEventListener("pointermove",pointer);window.removeEventListener("pointerdown",pointer);window.removeEventListener("touchstart",touch);window.removeEventListener("touchmove",touch);document.removeEventListener("visibilitychange",visibility);if(frameRef.current!==null)cancelAnimationFrame(frameRef.current)}},[]);
 const coverage=useMemo(()=>getOniRigAssetCoverage(),[]);const layers=useMemo(()=>ONI_RIG_LAYERS.map(l=>({...l,src:getOniRigAsset(l.id)})).filter(l=>Boolean(l.src)),[]);const layered=coverage.complete,exp=ONI_RIG_EXPRESSIONS[state],motion=ONI_WEB_LIVE2D_MOTIONS[state];
 const style:RigStyle={"--oni-look-x":"0","--oni-look-y":"0","--oni-glow":`${glow}`,"--oni-motion":`${ONI_RIG_STATE_INTENSITY[state]}`,"--oni-eye-open":`${exp.eyeOpen}`,"--oni-eye-smile":`${exp.eyeSmile}`,"--oni-pupil-scale":`${exp.pupilScale}`,"--oni-mouth-open":`${exp.mouthOpen}`,"--oni-mouth-smile":`${exp.mouthSmile}`,"--oni-blush":`${exp.blush}`,"--oni-head-tilt":`${exp.headTilt}deg`,"--oni-body-energy":`${exp.bodyEnergy}`,"--oni-live-head-x":`${motion.headX}`,"--oni-live-head-y":`${motion.headY}`,"--oni-live-head-z":`${motion.headZ}`,"--oni-live-body-x":`${motion.bodyX}`,"--oni-live-breath":`${motion.breath}`,"--oni-live-hair":`${motion.hair}`,"--oni-live-arm":`${motion.arm}`,"--oni-blink-rate":`${motion.blinkRate}s`,"--oni-talk-energy":`${speaking?1:motion.talk}`};
 return <div ref={rootRef} className={`oni-web-rig oni-web-rig--${state}${speaking?" is-speaking":""}${layered?" has-layered-art":""}`} style={style} aria-hidden="true" data-rig-mode={layered?"web-live2d-layered":"web-live2d-fallback"} data-rig-assets={`${coverage.available.length}/${coverage.total}`} data-expression={state}><div className="oni-web-rig__shadow"/><div className="oni-web-rig__aura"/><div className="oni-web-rig__body">{!layered&&<img src={oniCharacter} alt="" decoding="async" draggable={false} className="oni-web-rig__fallback"/>}{layered&&layers.map(l=><img key={l.id} src={l.src} alt="" decoding="async" draggable={false} className={`oni-web-rig__layer oni-web-rig__layer--${l.id} oni-web-rig__physics--${l.physics??"body"}`} style={{zIndex:l.z,transformOrigin:`${l.anchorX}% ${l.anchorY}%`}}/>)}{!layered&&<div className="oni-web-rig__face-life"><span className="oni-web-rig__eye oni-web-rig__eye--left"><i/></span><span className="oni-web-rig__eye oni-web-rig__eye--right"><i/></span><span className="oni-web-rig__mouth"/></div>}</div><div className="oni-web-rig__hair-flow"/><div className="oni-web-rig__particles"/></div>
}
